name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  speech_to_text: ^7.2.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.0
  geolocator: ^14.0.2
  image_picker: ^1.1.2
  geocoding: ^4.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
